name: FundamentalsXEconomy
version: 1.3.0
author: WiseHollow
main: com.wisehollow.fundamentalseconomy.Main
api-version: 1.13

load: startup
depend: [ FundamentalsX, Vault ]

commands:
      Econ:
               description: Manage other players wallet.
               usage: /<command> [set|give|take] [player] [amount]
      Balance:
               description: Check how much money a player has.
               usage: /<command> [player]
      Bal:
               description: Check how much money a player has.
               usage: /<command> [player]
      Pay:
               description: Can pay money to other players.
               usage: /<command> [player] [amount]


permissions:
      Fundamentals.Balance:
               description: Check your cash balance.
               default: op
      Fundamentals.Pay:
               description: Can pay money to other players.
               default: op
      Fundamentals.Economy.Loan:
               description: Allow a player to have a negative balance.
               default: op
      Fundamentals.Econ:
               description: Manage other players wallet.
               default: op
