name: FundamentalsXAntiGrief
version: 1.3.0
author: wisehollow
main: com.wisehollow.fundamentalsantigrief.Main

depend: [ FundamentalsX ]

permissions:
      Fundamentals.AntiGrief.Bypass:
               description: Bypass all checks.
               default: op