name: FundamentalsXAntiGrief
version: 1.3.8
author: wisehollow
main: com.wisehollow.fundamentalsantigrief.Main
api-version: 1.13

depend: [ FundamentalsX ]

permissions:
      Fundamentals.AntiGrief.Bypass:
               description: Bypass all checks.
               default: op