name: FundamentalsXChat
version: 1.3.6
author: wisehollow
main: com.wisehollow.fundamentalschat.Main
api-version: 1.13

depend: [FundamentalsX, Vault]
load: STARTUP

commands:
      Mute:
          description: Prevents a player from talking publicly.
          usage: /<command> <Player>

permissions:
      Fundamentals.Mute:
        description: Prevent a player from speaking publicly.
        default: op
      Fundamentals.ChatColor:
        description: Allows the use of colors in public chat.
        default: op