name: FundamentalsXChat
version: 1.3.1
author: wisehollow
main: com.wisehollow.fundamentalschat.Main
api-version: 1.13

depend: [FundamentalsX, Vault]
load: startup

commands:
      Mute:
          description: Prevents a player from talking publicly.
          usage: /<command> <Player>

permissions:
      Fundamentals.Mute:
               description: Prevent a player from speaking publicly.
               default: op